language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry composer require "php-coveralls/php-coveralls=^2.1" --prefer-dist --no-interaction --no-suggest --dev

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v